
@startuml consumer-provider
skin rose


participant "Consumer (P1)" as P1
participant "Consumer and Provider (P2)" as P2
participant "Provider (P3)" as P3

P1 -> P2
activate P2
    P2 -> P3
    activate P3
        P3 --> P2
    deactivate P3
    P2 --> P1
deactivate P2

@enduml